MonitoringTruck/Models/Datum.cs
using System;

namespace MonitoringTruck.Models
{
    public class Datum
    {
        public string NO_JOB { get; set; }
        public string STATUS_TERAKHIR { get; set; }
        public string STOWAGE_PLAN { get; set; }
        public double BERAT_IN { get; set; }
        public DateTime CREATION_DATE { get; set; }
        public string STOWAGE { get; set; }
        public DateTime LAST_UPDATE_DATE { get; set; }
        public string NO_PNTP { get; set; }
        public string LAST_UPDATE_BY { get; set; }
        public string NO_SPMK { get; set; }
        public string PLAT_NO { get; set; }
        public int? HARI { get; set; }
        public string SHIFT { get; set; }
        public string NO_PPK { get; set; }
        public string NM_KAPAL { get; set; }
        public double? NETTO { get; set; }
        public object? NM_SOPIR { get; set; }
        public string NM_PETUGAS_IN { get; set; }
        public string? NM_PETUGAS_OUT { get; set; }
        public int CETAK_KE { get; set; }
        public DateTime? GATE_IN_DATE { get; set; }
        public double? BERAT_OUT { get; set; }
        public string KD_KEGIATAN { get; set; }
        public DateTime? GATE_OUT_DATE { get; set; }
    }
}

MonitoringTruck/Models/ErrorViewModel.cs
namespace MonitoringTruck.Models
{
    public class ErrorViewModel
    {
#pragma warning disable CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
        public string? RequestId { get; set; }
#pragma warning restore CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MonitoringTruck/Models/Result.cs
using System.Collections.Generic;

namespace MonitoringTruck.Models
{
    public class Result
    {
        public int recordsFiltered { get; set; }
        public List<Datum> data { get; set; }
        public int draw { get; set; }
        public int recordsTotal { get; set; }
    }
}

MonitoringTruck/Models/Root.cs
namespace MonitoringTruck.Models
{
    public class Root
    {
        public Result result { get; set; }
        public string status { get; set; }
    }
}

MonitoringTruck/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MonitoringTruck.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MonitoringTruck.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MonitoringTruck/Controllers/TruckMonitoringController.cs
using Microsoft.AspNetCore.Mvc;
using MonitoringTruck.Models;
using MonitoringTruck.Services;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonitoringTruck.Controllers
{
    public class TruckMonitoringController : Controller
    {
        private readonly TruckMonitoringService _truckService;

        public TruckMonitoringController(TruckMonitoringService truckService)
        {
            _truckService = truckService;
        }

        public async Task<IActionResult> Index()
        {
            Root result = await _truckService.GetTruckData();
            //List<Datum> filteredData = result.result.data.ToList();

            return View(result);
        }
    }


}

MonitoringTruck/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MonitoringTruck/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonitoringTruck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MonitoringTruck</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TruckMonitoring" asp-action="Index">Truck Monitoring</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MonitoringTruck/Views/TruckMonitoring/Index.cshtml
@model Root

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <h1>Chart Data Truk yang Berkegiatan</h1>
        </div>
            
        <div class="col-md-12">
            <canvas id="myChart"></canvas>
        </div>

        <div class="col-md-12">
            <h2>Data Truk</h2>
            <div class="card">
                <div class="card-body" style="overflow: scroll">
                    <table id="truckTable" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Kode Truk</th>
                                <th>Nopol</th>
                                <th>No SPMK</th>
                                <th>Tgl Gate In</th>
                                <th>Tgl Gate Out</th>
                                <th>Time (Gate Out - Gate In)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.result.data)
                            {
                                <tr>
                                    <td>@item.NO_JOB</td>
                                    <td>@item.PLAT_NO</td>
                                    <td>@item.NO_SPMK</td>
                                    <td>@item.GATE_IN_DATE</td>
                                    <td>@item.GATE_OUT_DATE</td>
                                    <td>@(item.GATE_OUT_DATE.HasValue && item.GATE_IN_DATE.HasValue ? (item.GATE_OUT_DATE.Value - item.GATE_IN_DATE.Value).TotalHours.ToString() : "N/A")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            
        </div>

            
    </div>
        
</div>



@section Scripts {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
}



<script>
    $(document).ready(function () {
        $('#truckTable').DataTable();
    });

    const data = {
        labels: ['Gate In', 'Di Dalam', 'Gate Out'],
        datasets: [{
            label: 'Data Truk yang Berkegiatan',
            data: [@Model.result.data.Count(d => d.GATE_IN_DATE != null), @Model.result.data.Count(d => d.GATE_OUT_DATE == null && d.GATE_IN_DATE != null), @Model.result.data.Count(d => d.GATE_OUT_DATE != null)],
            backgroundColor: ['rgb(255, 99, 132)', 'rgb(54, 162, 235)', 'rgb(75, 192, 192)'],
        }]
    };

    const config = {
        type: 'bar',
        data: data,
        options: {
            responsive: true,
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, config);
    }
</script>